### ISSUE TITLE
Unlimited Quarantine? Why?

### ISSUE THREAD

**Issue by nosurveillance** [austrianredcross/stopp-corona-android#11]
What is the purpose of a never ending quarantine? Why would this exist?

https://github.com/austrianredcross/stopp-corona-android/blob/4e8816702ba1163f262b99abe55b470c8dd697d0/app/src/main/java/at/roteskreuz/stopcorona/model/repositories/QuarantineRepository.kt#L335-L338

**Comment by mitsuhiko** [comment]
That's used by the system to indicate a quarantine that has no defined end date. This for instance happens if you are tested covid-19 positive. Until you are tested negative you're not allowed to leave quarantine in Austria.

**Comment by nosurveillance** [comment]
Please reconsider naming conventions and functionality of this for trust reasons.

It's all about trust, this cannot be stressed enough. A method to keep a person notified indefinitely that he/she is under quarantine does not really help.

Also, how does this work in practice? Who removes this status and how? What checks are in place that nobody is quarantined "forever"?
