### ISSUE TITLE
Not compatible with moto g(6) running Android 9

### ISSUE THREAD

**Issue by johann-petrak** [austrianredcross/stopp-corona-android#150]
This is a comparably modern phone, runs Android 9, API Level 28,  has capable Bluetooth, 4GB RAM, 8 CPUs ...

So why is an app that is intended to be used by as many users as possible not compatible with this phone?

**Comment by mitsuhiko** [comment]
This is something that should be revisited after the changes to the Google/Apple framework. I'm not sure what the status of that system is on your particular phone however.

**Comment by johann-petrak** [comment]
How can the status of the Google framework be checked?  Do you refer to their exposure notification library?

The Google -> Covid19 notifications screen does not show any version information and I was not able to find anything in the applications list for com.google.android.apps.exposurenotification.*

**Comment by johann-petrak** [comment]
Google Play services are at version 20.18.17 (100308-311416286), updated on May 27th, if that helps.

**Comment by mitsuhiko** [comment]
The new version was released today. Can you see if the app is compatible with your device?

**Comment by johann-petrak** [comment]
Still not shown in the device's play store app (the app does not show incompatible apps at all), and on my desktop, the link https://play.google.com/store/apps/details?id=at.roteskreuz.stopcorona still says "This app is incompatible with all of your devices."

Could I ask again which framework version you were referring to and how it can be checked on my device?

**Comment by mitsuhiko** [comment]
Can you try to clear the android play store cache on your phone and install the app via your phone's play store instead of desktop? I don't see a good reason why the app shouldn't be compatible right now.

**Comment by dusanjencik** [comment]
@johann-petrak Hi, we needed to limit some HW devices due to requirement of Exposure notifications framework. Your device probably doesn't support it.

**Comment by marandaneto** [comment]
it might be a dup of #179

**Comment by johann-petrak** [comment]
> @johann-petrak Hi, we needed to limit some HW devices due to requirement of Exposure notifications framework. Your device probably doesn't support it.

What exactly is likely to be not be supported, or how to figure  what specifically is not supported on my device? It is hard to pin this down as long as my questions for what to check specifically are not getting answered. 

BLE is most probably supported since I am using a number of BLE devices like heartrate belts, cadence  and power meters with that device. 

If, as issue #179 indicates even other still commonly used devices like Samsung Galaxy S7 and Samsung Galaxy S7 Edge then the usefulness of this app is probably severely limited since a lot of people simply cannot use it (both of those DO have BLE according to their specification)

**Comment by treysis** [comment]
The error message is misleading. The problem occurs because u r not using Austrian PlayStore.

**Comment by johann-petrak** [comment]
> The error message is misleading. The problem occurs because u r not using Austrian PlayStore.

Why does this matter? I am using an Austrian provider sim, but my phone is set to UK English because that is the language I prefer. My current location is Vienna, Austria. 
I cannot remember that I have ever chosen which play store to use if there are several, and I would not know how to now choose a different one.

**Comment by treysis** [comment]
I don't know to what country the PlayStore defaults to if you have never set it. Maybe if u never entered a payment method and it is old enough it will not be bound to any country. I can only guess here. But your problem is that it must be set to Austria...or actually: the problem is that the app is only published in the Austrian store (which is neither requirement nor advisable, e.g. Switzerland, Italy, Latvia don't use country restrictions, Germany however suffers from the same problem).

**Comment by treysis** [comment]
You can check your current country in Burger menu -> Account -> Preferences (scroll down)

**Comment by mitsuhiko** [comment]
The geo lock restriction should be gone when the stores update. It has been lifted but it takes a while to propagate across all stores.

**Comment by johann-petrak** [comment]
> The geo lock restriction should be gone when the stores update. It has been lifted but it takes a while to propagate across all stores.

Oh right, thank you!
Turns out that I probably won't be able to change this, even to just check anything because 1) Google allows to only change this once a year, and 2) my google pay accounts would stop working, according to the Google help information for that page.

**Comment by treysis** [comment]
Ok, somebody must have made a mistake. The geolock is still in place.

**Comment by uliluckas** [comment]
App available in play stores world wide now

**Comment by johann-petrak** [comment]
Just to confirm: works for me now as well!
