### ISSUE TITLE
Re-Activation of automatic handshake if bluetooth was disabled

### ISSUE THREAD

**Issue by bauxi** [austrianredcross/stopp-corona-android#18]
## Description

I guess a typical use case of the every day user would be to enable flight mode when they go to bed. In the morning flight mode gets disabled again, bluetooth starts, BUT the automatic handshake of the app is not enabled automatically. Since the app should in the best case work with as less interaction as possible once the handshake is activated, the automatic handshake should start automatically, when bluetooth gets enabled on the phone.
Would this be possible from the Android side?

## Reproduction steps

1. Perform initial steps within the app and enable the automatic handshake
2. Turn off bluetooth
3. Turn on bluetooth
4. Verify that the automatic handshake in the app has been disabled

Additional helpful information:

- Version of the app: 1.1.4.11-QA_224

## What did you expect

The automatic handshake should stay enabled all the time with as less user interaction as possible. This means it should automatically turn on again, even if the phone has been put in flight mode temporarily or bluetooth has been turned off for some time.

**Comment by tiefenb** [comment]
Would be really great to see this as a feature or bugfix :-) Happens also on my Moto G7 Plus with Android 9

**Comment by uliluckas** [comment]
Upcoming version will use the Google/Apple framework and thereby completely reimplement the BT handling
