### ISSUE TITLE
Bring back traced contact list

### ISSUE THREAD

**Issue by bauxi** [austrianredcross/stopp-corona-android#190]
Is it possible to access the traced contacts from the OS? It would be nice to bring back the contact list like it was with the older versions of the app, or maybe show at least the number of handshakes made with other app users.

I think, this would increase the users' trust in the app since it shows that the app actually does something in the background. I think, it also would increase the overall interest in the app - if you look at the play store comments, so many people tried out the old automatic handshake, but it didn't work. now they could actually get kind of an Erfolgserlebnis. If it is not possible from the Google side, you can close this issue :)

**Comment by rdissertori** [comment]
yes, otherwise you won't be able to verify that the app is working. trust is very important - this should get high prio, because otherwise people won't use it.
ideally a filterable list of the local anonymized data should be feasable privacy and implementation wise

**Comment by MidnightDesign** [comment]
It would be helpful to have at least _some_ kind of indicator that it's doing something. Even if it's just a general "contacts in the last 24h" for a start.

**Comment by treysis** [comment]
@MidnightDesign This is not possible with the Google/Apple Contact-Tracing-API.

**Comment by mitsuhiko** [comment]
Yeah, would be nice to have but the APIs provided intentionally don't provide this information sadly.
