### ISSUE TITLE
Daily background exposure checks are not working

### ISSUE THREAD

**Issue by patloew** [austrianredcross/stopp-corona-android#197]
## Description

The app is installed and the handshake is enabled. However when I look in the Google system settings it's obvious that the app does not do daily exposure checks in the background. The last exposure check happened 3 days ago. When I open the app, a new exposure check entry is added to the list. Seems like the background check functionality is broken.

Additional helpful information:

- Version of the app: 2.0.3.1057 QA 245
- Phone: HUAWEI Mate 20 Pro / Android 10

![Screenshot_20200702_091800_com google android gms](https://user-images.githubusercontent.com/8015155/86329540-96165500-bc46-11ea-8c6c-b9970d95f63b.jpg)

**Comment by mitsuhiko** [comment]
It does check but it seems like both on Android and on iOS the checks are not happening reliably. See also https://github.com/austrianredcross/stopp-corona-ios/issues/107

**Comment by OrbitingOcelot** [comment]
Same issue with App version 2.0.3.1057 QA 245.

Checks only happen if app is opened manually. I have disabled all battery-optimization features of the OS in regards to the app but it is still not working.

As there will be a lot different manifestations of this issue depending on which OS flavour the users are using and many device manufacturerers have their own tweaks/settings, if this cannot be fixed reliably in code may I suggest a feature that checks on manual opening of the app if the app was able to download diagnosis keys previously in an unattended way. If not, advise the user of an issue with energy savings settings and provide further guidance/pointers for major OS variants to disable the conflicting features.

**Comment by cproof** [comment]
Can confirm the same problem on a Xiaomi Mi5 (Android 8, app version 2.0.3.1057-QA_245), energy saving disabled for the app. It only seems to synchronize when the app is manually opened.
![rk](https://user-images.githubusercontent.com/4948782/87519296-b05a2500-c681-11ea-8c73-df682e93e0b6.png)

**Comment by patloew** [comment]
Is this being worked on? It's been over three weeks and the problem is still not solved. I excluded the app from both HUAWEI specific battery optimizations and the Android system ones. Still, I need to open the app every other day to enable background checks again.

**Comment by NeroBurner** [comment]
https://dontkillmyapp.com/huawei

Maybe Huawei's Powergenie is at fault. Killing everything in the background which is not in Huawei's allowlist. With no user prevention possible

**Comment by lazka** [comment]
Same problem on my Xiaomi Poco F1. Enabling the "Autostart" permissions for the app seems to make it work though. Prior to that I had one week without any recorded checks.

I've only had one app (torrent client) on my phone which correctly detects that it's being killed and prevented to start and shows a warning to me. Here is where it seems to handle this, maybe this helps.. https://gitlab.com/axet/android-torrent-client/-/blob/HEAD/app/src/main/java/com/github/axet/torrentclient/activities/MainActivity.java#L559

**Comment by scientress** [comment]
This is not a Huawei specific problem, also happens on my OnePlus 5T with the heavy battery optimization of Oxygen OS switched off.
Oxygen OS: 9.0.11 
App Version: 2.0.3.1057-QA_245

**Comment by OrbitingOcelot** [comment]
On a Xiaomi phone with MIUI 11 I have manage to fix this issue by:
1. Giving the app the "autostart" permission
2. Setting the app energy profile to "no restrictions"

**Comment by steffyP** [comment]
Same problem on MIUI 12.0.1

I already disabled battery optimization, but that didn't work either. (I will also try setting "autostart" permission thanks @OrbitingOcelot).

This is a huge issue! Please fix this! Or at least provide some kind of guide, so that people installing the app are able to configure the app in a way that it will actually work. 

People that are not that tech-savvy will only rely that the app works, once they installed it.

**Comment by uliluckas** [comment]
Please retry with upcoming v2.0.5.
I'll close the ticket. Please report again if you still see issues.

**Comment by wis775** [comment]
Same Issue on Samsung Galaxy A5.

When will 2.0.5 be released? Actual App Version 2.0.4.1060-QA_248

**Comment by wis775** [comment]
Seems, that 2.0.5 is released. Now, it works.
