### ISSUE TITLE
Number of keys is zero with activated handshake

### ISSUE THREAD

**Issue by patloew** [austrianredcross/stopp-corona-android#198]
## Description

I have activated the handshake for a few days already and also spent some time nearby people with the iOS version of the app. For them, the number of keys is already >1000 (as shown in their iOS exposure check details). For me it still shows 0, even though I was near them for a considerable amount of time. Is the handshake working correctly?

Additional helpful information:

- Version of the app: 2.0.3.1057 QA 245
- Phone: HUAWEI Mate 20 Pro / Android 10

![Screenshot_20200702_092439](https://user-images.githubusercontent.com/8015155/86352347-f2d53800-bc65-11ea-95aa-55876dbce4b7.jpg)

**Comment by patloew** [comment]
This seems to work now after a play services update (version 202613000). Newer entries show a value > 0 for "Number of keys".

**Comment by bauxi** [comment]
Well, it's the same behavior for me: number of keys = 0 for all entries. My play services are at 20.21.17 - no update available (at least on my device)...

**Comment by flof93** [comment]
Got the same problem, would consider reopening this issue.

I'm on a Pixel 3A,
App version is QA245
Play Services is on version 20.24.14 (120400-319035315)
In the Corona-Exposure Settings it says version 202414000.
And there are no updates available for the services mentioned above.

**Comment by bauxi** [comment]
Does this mean that the Corona tracking still doesn't work, because the keys are not being pulled from the server? Or is it just a UI problem and it works correctly in the background (I'd hope for this option, but I am sceptical)?

I'd consider reopening the issue as well until this is fixed.

**Comment by flof93** [comment]
@patloew are you part of the beta-program for the play services? Because on apkmirror [1] the version you mentioned in your 2. comment is marked as beta.

If so, I think this bug is about to solve it self, when the  next play-services release comes...

[1] https://www.apkmirror.com/apk/google-inc/google-play-services/#variants

**Comment by bauxi** [comment]
Okay, according to this comment (https://github.com/corona-warn-app/cwa-app-android/issues/744#issuecomment-650532041), it seems like this is actually only a display bug, which is fixed in the next play services version 20.26.x... this is good to know :)
