### ISSUE TITLE
App prescribes self-quarantine which ends in the past

### ISSUE THREAD

**Issue by OrbitingOcelot** [austrianredcross/stopp-corona-android#206]
On July 25th, the App told the user to self-quarantine until July 15th. So basically the app prescribed a self-quarantine that already ended in the past.

![8d8c140c-da76-4436-a106-4dde47f07f82](https://user-images.githubusercontent.com/67998808/88514001-9ad1ed00-cfe9-11ea-9174-eb1f7433d634.jpg)

Note: the users Android phone (Xiaomi/MIUI11) only showed 1 background check in a timeframe over 14 days, might be related to aggressive battery management, so I suspect this error happens if the app retrieves diagnosis keys that are stale.

I would suggest adding a sanity-check and discard quarantine notices that are already obsolete.

**Comment by TuxCoder** [comment]
think is already fixed but not published: https://github.com/austrianredcross/stopp-corona-android/pull/203

**Comment by uliluckas** [comment]
@TuxCoder is right. This will be fixed in the upcoming release which is currently in QA.
