### ISSUE TITLE
App may fail to notify exposed users due to aggressive OEM battery saving measures

### ISSUE THREAD

**Issue by marandaneto** [austrianredcross/stopp-corona-android#207]
Pretty much the same as the German App.

https://www.androidpolice.com/2020/07/24/covid-19-tracing-apps-may-fail-to-notify-exposed-users-due-to-aggressive-oem-battery-saving-measures/

I'd suggest adding a toggle that lets users allow the app to always run in the background.

On my Sony XPERIA for example, I've done it manually.

![Screenshot_20200731-094120](https://user-images.githubusercontent.com/5731772/89012240-290fe100-d312-11ea-92dd-f5f92408268f.png)

**Comment by marandaneto** [comment]
probably being addressed by #212

**Comment by uliluckas** [comment]
Fixed in 2.0.5
