### ISSUE TITLE
Exposure Checks stopped - No exposure checks within the last 14 days even though app is running

### ISSUE THREAD

**Issue by steffyP** [austrianredcross/stopp-corona-android#223]
## Description

The app seems not to do the "exposure checks" anymore. I realized a few days back, that the last successful exposure check (the one you can check in Settings -> Google -> Exposure Notifications -> Exposure Checks), was on 16th September. 
Today, 4th October, I don't see ANY Exposure Checks at all. 

## Reproduction steps

1. App is running, Automatic handshake enabled
2. Disabled battery optimizaton
3. Allowed Autostart
4. Pinned in Task manager, so it will not get killed accidentially
5. Also tried to dis- and re-enable the automatic handshake -> nothing happens

Additional helpful information:

- App Version: 2.0.4.1060-QA-248
- Device: Mi 9T Pro with MIUI Global 12.0.2, Android version 10 QKQ1.190825.002
- I had some problems before, probably due to battery optimization. The app would just stop doing the exposure checks, but would also work again, once I manually opened the app. Which is now not the case.
- I also tried to delete the app data.

## What did you expect

I expect the app to regularly do the exposure checks like it did before.

**Comment by steffyP** [comment]
Update: Force stop + deleting app data seemed to temporarly solve the issue. At least I got a few "exposure checks" counts today.

**Comment by steffyP** [comment]
App stopped doing exposure checks again. According to the logs, it worked from 4th October until 9th October 21:30.

Is there anything I could do to make this app work permanently? 
It is really annoying to check manually everyday if it still working, and re-install it, in case it doesn't.

Is anyone else experiencing this weird issue? Is it working on other devices?

**Comment by wis775** [comment]
Same Issue on my Galaxy A6.
Still waiting for version 2.0.5 as mentioned in #197

**Comment by wis775** [comment]
In the meantime, I got Version 2.0.5. For me, the issue seems to be fixed.

**Comment by steffyP** [comment]
Seems like the update indeed fixed the problem. Thanks :)
