### ISSUE TITLE
Certificate pinning for all communication

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#23]
Currently only the communication with the server ```rca-coronaapp-rcp-fd.azurefd.net``` is protected by certification pinning. 
For all other communication paths (Google, p2pkit...) mitm attacks are still possible.

Proposed solution:

Add a ```security config``` for the app.

Ref https://developer.android.com/training/articles/security-config

**Comment by mitsuhiko** [comment]
I believe this is going to become a wontfix for most communication. The reason being that for p2pkit and other services there is the red cross does not control those certificates. However going forward those services should be removed as the architecture is moved to further decentralization.
