### ISSUE TITLE
Disable code obfuscation

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#24]
Currently the code is obfuscated during build time using proguard.
Which classes are obfuscated is defined in `core/proguard-rules.pro`.

There is no reason for obfuscation in an open source project.

Proposed solution: remove obfuscation config

**Comment by Peeeep** [comment]
While I fully agree that obfuscation itself is unnecessary in an open source project, proguard is primarily a tool for tree-shaking (code shrinking) and optimizing, thus potentially reducing the file size of apps.

The publication of the `mapping.txt` file along a release would allow anyone to de-obfuscate stack traces whilst keeping the optimizations in place.

**Comment by mitsuhiko** [comment]
I am pretty sure kicking out proguard entirely will probably not be a great idea due to the stated reasons, but sharing the `mapping.txt` is a good idea.

**Comment by hoeggi** [comment]
One can still use proguard with -dontofuscate to have optimiztion and tree-shaking but without obfuscation.

**Comment by mrqc** [comment]
If somebody is interested in a runtime analysis with captured runtime strings, I created bcz of my interest in disassembling android apps. Here you will find a link. You can find the URL endpoints, SQL statements, stored data, other strings like API keys and so on: https://github.com/mrqc/stopcorona-runtime-analysis/blob/master/debug.log

**Comment by mrqc** [comment]
If somebody is interested in a runtime analysis with captured runtime strings I created bcz of my interest in disassembling android apps, here you will find a link. You can find the URL endpoints, SQL statements, stored data, other strings like API keys and so on: https://github.com/mrqc/stopcorona-runtime-analysis/blob/master/debug.log

**Comment by stefan2904** [comment]
I think this also makes sense as part of the DP3T integration.

**Comment by uliluckas** [comment]
Fied in upcoming v2.0.5. Thanks @simonschiller!
