### ISSUE TITLE
timestamp vs. iso date

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#25]
Times should be saved in one format.
Currently is unix timestamps and iso date time mix in the code

`prefs.xml`
```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="pref_offline_sync_last_config_sync_time" value="1588171947081" />
    <long name="pref_offline_sync_last_infection_messages_sync_time" value="1588171947650" />
...
    <string name="pref_terms_and_conditions_repository_data_privacy_timestamp_v1.1">2020-04-27T19:47:45.871+02:00[Europe/Vienna]</string>
    <string name="pref_questionnaire_compliance_repository_compliance_accepted_timestamp">2020-04-28T00:33:35.499+02:00[Europe/Vienna]</string>
    <string name="pref_terms_and_conditions_repository__data_privacy_timestamp">2020-04-27T19:47:45.868+02:00[Europe/Vienna]</string>
...
</map>
```

It is easy to handle and to program with only one format.

Also probably remove this external package `org.threeten` because we don't do fancy datetime calculation.

Proposed solution: use one kind of datetime handling in the whole app.

**Comment by mitsuhiko** [comment]
Going to close this as wontfix. There is no benefit to either users or the code base to unify the date time handling here. You are correct that this could be unified, but in the grand scheme of things it's unlikely time will be spent on this and it would require a migration.
