### ISSUE TITLE
Inconsistent handling of sum declared sick (red-warning) and self test (yellow-warning)

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#28]
## Description

The sum of declared sick (red-warning) and self test (yellow-warning) from the dashboard is not the same compared to detail page.

## Reproduction steps

Add some `infection_messages` to the database.

Here are some sample screenshots from the result shown in the app:

![Screenshot_20200429-182141_Stopp_Corona](https://user-images.githubusercontent.com/2470864/80624210-a6922f80-8a4b-11ea-92f6-5e855b8227eb.png)

dashboard:
* sum of all contacts: 952
* red-warning: 510
* yellow-warning: 428

510 + 428 =/= 952 👎

![Screenshot_20200429-182210_Stopp_Corona](https://user-images.githubusercontent.com/2470864/80624216-a7c35c80-8a4b-11ea-9ed2-a614e4a29f6a.png)
![Screenshot_20200429-182234_Stopp_Corona](https://user-images.githubusercontent.com/2470864/80624217-a7c35c80-8a4b-11ea-948c-41753cb66a46.png)

detail page (click on `Quarantäne-Tage`):
* sum of infected: 947
* red-warning: 510
* yellow-warning: 437

510 + 437 = 947 👍

947 =/= 952 👎
  
click on `Digitaler Handshake` `952` shows a list of all contacts which include dates older than 10 days.

detail page (click on `Quarantäne-Tage`):
* sum of infected: 947
* red-warning: 510
* yellow-warning: 437

510 + 437 = 947 👍

947 =/= 952 👎
  
click on `Digitaler Handshake` `952` shows a list of all contacts which include dates older than 10 days.

Proposed solution: 
* one consistent handling of sums
* data from the future should *NOT* count (example see [image2][image3])

**Comment by uluckas** [comment]
Hi @TuxCoder,
I do not understand the problem yet. Why do you expect the sum of contacts with infections and suspected infections (947) to equal the number of all your contacts (952)?
If I understand right, the numbers are just telling you that 5 of your contacts are fine and do not suspect a corona infection.

**Comment by devnsec** [comment]
I see what you mean but anyway what you see in the screenshots is a wrong calculation.
On the dashboard the number of "suspects" is 428 but in the detail view it's 437. 
Another test with more "infected" such a problem occured also for them. 

With the differences in the sum (5 of my contacts are fine) you are right.

Another point for me was that the lists are so long when you meet more people and without filtering by day and/or sorting by date it's useless to show these lists.

**Comment by uluckas** [comment]
Thanks for the clarification.
These lists will be reworked or removed during the switch to google's tracking framework.

**Comment by tinkercnc** [comment]
Hi @TuxCoder 

where has your Issue "Remove P2Pkit #32" gone?

**Comment by devnsec** [comment]
@tinkercnc the issue #32 was moved to a private repo. nobody know why. It looks for me that the decision making process is very intransparent when it comes to interesting topics...

**Comment by tinkercnc** [comment]
@devnsec 
Yes, I agree with you.
But it's typical for such datamining apps. ;)

**Comment by devnsec** [comment]
@tinkercnc I think that RK and Accenture did not know in detail what p2pkit is doing on there own to make the system work. We reversed it completely and it's not something you want to have in an app that tries to protect user relationships and provide anonymity. And because they pay for p2pkit (~0.01€ per active user per month) it's not easy to change old decisions and remove it before google and apple are ready.

**Comment by tinkercnc** [comment]
Maybe the Uepaa AG is a successor model of the Crypto AG... ;)

**Comment by tinkercnc** [comment]
from the p2pkit site: 
"Exchange with nearby devices. Imagine a restaurant publishing its menu to nearby diners or professionals sharing their business cards with fellow attendees at events: p2pkit allows you to seamlessly broadcast content to nearby devices."

Is seamlessly the new euphemistic replacement for concealed?

**Comment by uliluckas** [comment]
Issue is no longer relvant for v2 of the app
