### ISSUE TITLE
Misspelling in German Strings

### ISSUE THREAD

**Issue by mbangerl** [austrianredcross/stopp-corona-android#30]
I found a few misspelling phrases inside file  stopp-corona-android/app/src/main/res/values-de/strings.xml 

The errors are in the following phrases:
questionnaire_examine_headling_1 --> "Symptom" instead of "Symptome"
questionnaire_guideline_contact_info3  --> double space

**Comment by uluckas** [comment]
Thanks @mbangerl for pointing out.
This will be fixed in next release.
