### ISSUE TITLE
no internet connection

### ISSUE THREAD

**Issue by collab-appsdev** [austrianredcross/stopp-corona-android#36]
every time i click on report status and click next it always says no internet connection..

i am new to native in android what is the use of the code below and where can i get it?

object API {

        const val HOSTNAME = "insert_hostname"
        const val BASE_URL = "https://$HOSTNAME/Rest/v5/"

        val CERTIFICATE_CHAIN = listOf(
            "sha256/insert_pub_key_hash1",
            "sha256/insert_pub_key_hash2",
            "sha256/insert_pub_key_hash3"
        )

        object Header {
            const val AUTHORIZATION_VALUE = "insert_header_authorization_value"
        }
    }

**Comment by geekazoid-at** [comment]
It builds an object which it uses for connection. I guess you're not supposed to use their backend, thus you see placeholder values in the snippet.

**Comment by mitsuhiko** [comment]
The credentials are currently not exposed to avoid accidental abuse of the system. We will however put the backend code out soon then it should be easier to connect to something.

I'm going to close this issue as I don't believe it to be actionable.

**Comment by collab-appsdev** [comment]
can you please explain how firebase messaging push notifications on the persons who had a close contact with a covid positive patient that uses this app?

and what data are needed to be saved on the backend?
