### ISSUE TITLE
Project can not be build because of failing Gradle task

### ISSUE THREAD

**Issue by eggeral** [austrianredcross/stopp-corona-android#5]
## Description

Project can not be build because of failing Gradle task. (Calling git)
 - Process 'command 'git'' finished with non-zero exit value 128

## Reproduction steps

1. git@github.com:austrianredcross/stopp-corona-android.git
2. cd stopp-corona-android
3. ./gradlew clean build

Additional helpful information:

19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build completed with 2 failures.
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 1: Task failed with an exception.
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Script .../stopp-corona-android/gradle/base.gradle' line: 20
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating project ':app'.
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command 'git'' finished with non-zero exit value 128
19:35:31.505 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 

## What did you expect

Build runs through without failures.

**Comment by eggeral** [comment]
Workaround:

run 

`git tag test-tag

to create a tag so that 'git describe --tags` runs without errors

**Comment by uluckas** [comment]
Thanks @eggeral for pointing out. Tag created
