### ISSUE TITLE
p2pkit maven repo uses insecure plain HTTP connection

### ISSUE THREAD

**Issue by eighthave** [austrianredcross/stopp-corona-android#54]
## Description

This build uses plain HTTP to download code from the open internet: _build.gradle_ has `http://p2pkit.io/maven2` set as a maven repo. Maven repos should always be HTTPS.  See this for more info:

https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/

**Comment by mitsuhiko** [comment]
You are not wrong! Unfortunately p2pkit does not provide an https version of their maven repo. This issue should be solved when p2pkit is faced out. See also https://github.com/austrianredcross/meta/issues/3
