### ISSUE TITLE
Current app on Google Play contains tracking code

### ISSUE THREAD

**Issue by nosurveillance** [austrianredcross/stopp-corona-android#6]
## Description

At the time of writing this issue the App available on Google Play is Version 1.1.3.10-QA_223.
This version contains tracking code.

## Reproduction steps

1. Download App from Google Play
2. ???
3. Get tracked!

Additional helpful information:

- Screenshots
![Screenshot_2020-04-24_21-05-53](https://user-images.githubusercontent.com/64281419/80248039-b16d4e80-865e-11ea-8e6d-b62eb2867eaf.png)
![Screenshot_2020-04-24_21-06-53](https://user-images.githubusercontent.com/64281419/80248140-db267580-865e-11ea-8568-dcc345faf78f.png)

- 1.1.3.10-QA_223

## What did you expect

App on Google Play should match this source and NOT CONTAIN TRACKING CODE!

**Comment by evilscientress** [comment]
Where you able to verify that that method is actually used?
It's something that should not happen in an app like that, but it could actually be a honest mistake.
As in, that the wrapper method for the API call is still in there but it's no longer used.

**Comment by nosurveillance** [comment]
Didn't bother to check if it's still being used tbh.
The endpoint at https://rca-coronaapp-rcp-fd.azurefd.net/Rest/v4/track-events throws a 404 (doesn't mean anything though, in case the data is still sent).

As you stated in #3 they said it had been removed with the "latest" update, which was 1.1.2.9-QA_221 at the time.

This method was in use before and the data DID get collected AND allowed for quite some analysis and de-anonymization of contacts there is no base for any kind of trust in this app until this is completely resolved.

**Comment by mitsuhiko** [comment]
Just a heads up: the version of the app in this repository is being released to the play store at the moment.

**Comment by mitsuhiko** [comment]
Version is released now.
