### ISSUE TITLE
Generate and show ID for Offline-Tracking

### ISSUE THREAD

**Issue by romanseidl** [austrianredcross/stopp-corona-android#67]
**Feature**
The app allows the user to show an ID on the screen, best also in machine readable form (i.e. barcode). This ID can be used as an alternative to providing regular contact data (e.g. phone number and name) for Offline-Tracking.

**Use case**
More and more places such as theaters etc. will be recomended or even obliged to collect contact data of visitors to allow for tracing in case of an infection. The app could provide for a voluntary means of tracking and tracing with a higher standard in data protection. 

**Implementation**
The feature should be quite straightforward to implement. The app is already generating IDs that are broadcast via Bluetooth. The only necessary should be the possibility to show such an ID in a human readable (and best also machine readable) form on the display.

**Comment by falkorichter** [comment]
This feature request is obsolete as we´re using the Google Apple Exposure Notifications framework and it does not allow for such manual key exchange.
