### ISSUE TITLE
Support for DP3T 

### ISSUE THREAD

**Issue by wischi-chr** [austrianredcross/stopp-corona-android#68]
DP3T is a truly open source and privacy first implementation of contact tracing (Switzerlands official contact tracing app uses it) - https://github.com/DP-3T/documents

IMHO the stopp corona app should implement DP3T or even fork switzerlands app for better privacy and true open source which is essential for apps like these.

**Comment by mitsuhiko** [comment]
Adopting the Google/Apple Tracing Infrastructure is being scheduled (https://github.com/austrianredcross/meta/issues/3). These APIs are largely influenced by the DP-3T design and also permit the collection of exposure notifications with the application in background. Work is currently ongoing to move the implementation over to there.

For discussions about the tracing technology I would love to direct you to the meta repository: https://github.com/austrianredcross/meta
