### ISSUE TITLE
Server code is missing

### ISSUE THREAD

**Issue by nosurveillance** [austrianredcross/stopp-corona-android#7]
## Description

Server code is not available

## What did you expect

Server code should be available

**Comment by mitsuhiko** [comment]
The server code will come too but will take more time. I'm going to close the issue here as this is the android repository. We will open a meta repo for such issues later.

**Comment by gstarnberger** [comment]
@nosurveillance @mitsuhiko FYI: I just released my own implementation of the server on https://github.com/gstarnberger/covidsrv. It's quite simple at the moment (basically a prototype), but contains sufficient functionality to test most features of the apps.

**Comment by devnsec** [comment]
> @nosurveillance @mitsuhiko FYI: I just released my own implementation of the server on https://github.com/gstarnberger/covidsrv. It's quite simple at the moment (basically a prototype), but contains sufficient functionality to test most features of the apps.

@gstarnberger I added some message samples to your repo as issues

**Comment by gstarnberger** [comment]
@devnsec Thanks! I'll use those samples to add some tests.
