### ISSUE TITLE
Disclosure in README

### ISSUE THREAD

**Issue by nosurveillance** [austrianredcross/stopp-corona-android#8]
Highlighted part of screenshot should not be hidden under "Medical confirmation".

![Screenshot_2020-04-24_22-30-22](https://user-images.githubusercontent.com/64281419/80254375-91438c80-866a-11ea-8597-b276d68bc68e.png)

**Comment by mitsuhiko** [comment]
We will revise the readmes early next week. There are also inconsistencies with the one from iOS.
