### ISSUE TITLE
minSdkVersion should be 21 or lower

### ISSUE THREAD

**Issue by marandaneto** [austrianredcross/stopp-corona-android#9]
Ideally, minSdkVersion should be 21 (Lollipop) or lower, currently it's 23 (Marshmallow).
This would increase ~10% of compatibility with older devices.

![Screenshot 2020-04-24 at 22 49 43](https://user-images.githubusercontent.com/5731772/80256132-8692f280-867e-11ea-84cc-b294299d4ae9.png)

**Comment by mobilekosmos** [comment]
Ideally all devices worldwide would be on API 29.

**Comment by marandaneto** [comment]
> Ideally all devices worldwide would be on API 29.

maybe in ~6 years :)

**Comment by uliluckas** [comment]
Google exposure notification framework is not supported below API 23

**Comment by marandaneto** [comment]
true, just for the record, I've asked on Google's sample about this, they have minApi 21, but their docs state minApi 23
https://github.com/google/exposure-notifications-android/issues/36

**Comment by treysis** [comment]
> Google exposure notification framework is not supported below API 23

Why do I see it on my API 21 device in the PlayServices settings?
